### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by vsimko** [jeffwidman/bitbucket-issue-migration#73] opened 2016-03-07 16:29 UTC
``` sh
Traceback (most recent call last):
  File "/path/to/migrate.py", line 490, in <module>
    sys.exit(main(options))
  File "/path/to/migrate.py", line 179, in main
    gh_issue, gh_comments, options.github_repo, options.gh_auth, headers
  File "/path/to/migrate.py", line 438, in push_github_issue
    respo = requests.post(url, json=issue_data, auth=auth, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by jeffwidman** [comment] 2016-03-07 18:49
Most likely a dupe of #61 - you'll need to update your version of the `requests` library.

**Closed by jeffwidman** 2016-03-07 18:49 UTC
